#!/usr/bin/env bash
# Regenerates dns/team-dnsmasq.conf and nginx/nginx.conf from env.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/env.sh"
BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /opt/homebrew)"
CERT_DIR="$BREW_PREFIX/etc/nginx/certs"

cat > "$ROOT/dns/team-dnsmasq.conf" <<EOF
# Mac 1 - private DNS for ${DOMAIN}
# GENERATED by scripts/render-configs.sh from env.sh - edit env.sh, not this file.
port=53
listen-address=127.0.0.1,${MAC1_IP}
bind-interfaces
# Do not read /etc/resolv.conf or /etc/hosts: only what is written here + explicit upstreams
no-resolv
no-hosts
server=${UPSTREAM_DNS_1}
server=${UPSTREAM_DNS_2}
# Names under ${DOMAIN} are answered ONLY by us (never forwarded to the internet)
local=/${DOMAIN}/
local-ttl=30
host-record=app.${DOMAIN},${MAC2_IP}
host-record=api.${DOMAIN},${MAC2_IP}
# Log every query to the terminal (great live evidence)
log-queries
log-facility=-
EOF

cat > "$ROOT/nginx/nginx.conf" <<EOF
# Mac 2 - edge: TLS termination + reverse proxy + round-robin load balancer
# GENERATED by scripts/render-configs.sh from env.sh - edit env.sh, not this file.
worker_processes 1;
error_log /tmp/nginx-cn-error.log info;
pid       /tmp/nginx-cn.pid;

events { worker_connections 256; }

http {
    default_type application/json;

    # Which backend answered each request (for the viva + evidence)
    log_format cn '\$remote_addr:\$remote_port [\$time_local] "\$request" \$status '
                  'upstream=\$upstream_addr upstream_status=\$upstream_status X-Backend=\$upstream_http_x_backend';
    access_log /tmp/nginx-cn-access.log cn;

    # ---- UPSTREAM POOL (default method = round-robin) ----
    upstream app_pool {
        server ${MAC3_IP}:${BACKEND_A_PORT} max_fails=1 fail_timeout=5s;   # Backend A (Mac 3)
        server ${MAC4_IP}:${BACKEND_B_PORT} max_fails=1 fail_timeout=5s;   # Backend B (Mac 4)
    }

    server {
        listen ${HTTPS_PORT} ssl;
        server_name app.${DOMAIN} api.${DOMAIN};

        # ---- TLS terminates HERE ----
        ssl_certificate     ${CERT_DIR}/edge.pem;
        ssl_certificate_key ${CERT_DIR}/edge-key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;     # client picks; use curl --tls-max 1.2 for the classic handshake capture

        location / {
            proxy_pass http://app_pool;
            proxy_set_header Host              \$host;
            proxy_set_header X-Real-IP         \$remote_addr;
            proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_connect_timeout 2s;
            proxy_next_upstream error timeout;  # if one backend refuses/times out, retry on the other
        }
    }
}
EOF
echo "Rendered:"
echo "  $ROOT/dns/team-dnsmasq.conf"
echo "  $ROOT/nginx/nginx.conf"
